#! /bin/sh

set -e

bind_mounts () {
    # set defaults
    test -z "$tmpfs_dir" && tmpfs_dir=/var/lib/ltsp-client-setup
    mkdir -p "$tmpfs_dir"
    mount -t tmpfs -o mode=0755 tmpfs $tmpfs_dir
    bind_missing=""
    # preserve directory structure
    for d in $rw_dirs ; do
        if [ -d "$d" ]; then
            cd $tmpfs_dir
            tar --no-recursion -cpf - $(find $d -type d 2> /dev/null) 2> /dev/null | tar xpf -
            mount --bind $tmpfs_dir/$d $d
        else
            bind_missing="$bind_missing $d"
        fi
    done
    # copy contents into tmpfs
    for d in $copy_dirs $temp_copy_dirs; do
        if [ -d "$d" ]; then
            cd $tmpfs_dir
            tar -cpf - $d 2> /dev/null | tar xpf -
            mount --bind $tmpfs_dir/$d $d
        else
            bind_missing="$bind_missing $d"
        fi
    done
    # mount one file on top of another
    for f in $bindfiles ; do
        if [ -e "$f" ]; then
            mkdir -p "$(dirname $tmpfs_dir/$f)"
            cp $f $tmpfs_dir/$f
            mount --bind $tmpfs_dir/$f $f
        else
            bind_missing="$bind_missing $f"
        fi
    done
    if [ -n "$bind_missing" ]; then
        echo "note: ltsp: missing files or directories for bind mounting: $bind_missing"
    fi
}

bind_unmounts() {
    for dir in $temp_copy_dirs; do
        umount $dir
        rm -rf $tmpfs_dir/${dir#/}
    done
}

# tmpfs/bind directories that get mounted with only directory structure
# preserved

rw_dirs="/etc/console-setup /tmp /var/cache /var/cache/hald /var/cache/ltsp /var/crash /var/lib/dbus /var/lib/pulse /var/lib/urandom /var/lib/xkb /var/log /var/spool /var/tmp"

# tmpfs/bind directories that get mounted with directory structure and data
# copied
copy_dirs="/etc/cron.d /etc/cron.daily /etc/cron.hourly /etc/cron.monthly /etc/cron.weekly /etc/cups /etc/default /etc/init /etc/init.d /etc/rc0.d /etc/rc1.d /etc/rc2.d /etc/rc3.d /etc/rc4.d /etc/rc5.d /etc/rc6.d /etc/rcS.d /etc/resolvconf /etc/rsyslog.d /etc/systemd/system /etc/udev/rules.d /etc/update-motd.d /home /lib/systemd/system /media /root /var/lib/ureadahead"

# tmpfs/bind files that mounted on top of other files
bindfiles="/etc/crontab /etc/fstab /etc/group /etc/hostname /etc/hosts /etc/localtime /etc/login.defs /etc/network/interfaces /etc/ntp.conf /etc/passwd /etc/rc.local /etc/resolvconf /etc/resolv.conf /etc/syslog.conf /etc/X11/xorg.conf"

if [ -f /etc/lts.conf ] && [ -x /usr/bin/getltscfg ]; then
    # get defaults from lts.conf
    eval $(/usr/bin/getltscfg -a)
fi

# override variables if configured via lts.conf or ltsp_config
[ -n "$LTSP_RW_DIRS" ] && rw_dirs="$LTSP_RW_DIRS"
[ -n "$LTSP_RW_DIRS_EXTRA" ] && rw_dirs="$rw_dirs $LTSP_RW_DIRS_EXTRA"
[ -n "$LTSP_COPY_DIRS" ] && copy_dirs="$LTSP_COPY_DIRS"
[ -n "$LTSP_COPY_DIRS_EXTRA" ] && copy_dirs="$rw_dirs $LTSP_COPY_DIRS_EXTRA"
[ -n "$LTSP_BINDFILES" ] && bindfiles="$LTSP_BINDFILES"
[ -n "$LTSP_BINDFILES_EXTRA" ] && bindfiles="$rw_dirs $LTSP_BINDFILES_EXTRA"

bind_mounts
