#!/bin/sh

. /usr/share/ltsp/ltsp-client-functions

if [ "$debug" != "${0##*/}" ]; then
    # We don't want init-ltsp to halt on errors unless we're debugging it
    set +e
fi

scriptsdir="/usr/share/ltsp/init-ltsp.d/"

# workaround Debian bug in initramfs-tools:
# http://bugs.debian.org/660297
mountpoint -q /sys || mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
mountpoint -q /proc || mount -t proc -o nodev,noexec,nosuid proc /proc

# Provide an ltsp.break=<script-name> kernel parameter which will offer a shell
# right before sourcing that script.
for x in $(cat /proc/cmdline); do
    case "$x" in
        ltsp.break=[0-9][0-9]-*)
            breakscript="$scriptsdir/${x#break=}"
            break;
            ;;
    esac
done

for script in $(run_parts_list "$scriptsdir") ; do
    if [ "${script##*/}" = "$breakscript" ]; then
        warn "Spawning shell before $script"
        bash -l
        warn "Continuing ltsp-init execution"
    fi
    debug "Sourcing $script"
    . "$script"
done

debug "Done"

# init=/sbin/init-ltsp can be used to launch this script, which should then
# chain to /sbin/init.
# To run it from the initramfs instead, set the EXEC_INIT environment variable
# to "false".
if [ "$EXEC_INIT" != "false" ]; then
    exec /sbin/init
fi
