#!/bin/sh

. /usr/share/ltsp/ltsp-common-functions
test -f "/etc/ltsp/initramfs-scripts.conf" && . /etc/ltsp/initramfs-scripts.conf

VENDOR=${VENDOR:-$(detect_vendor)}
if [ -d "/usr/share/ltsp/initramfs-scripts.d/$VENDOR" ]; then
    scriptsdir="/usr/share/ltsp/initramfs-scripts.d/$VENDOR"
elif [ -d "/usr/share/ltsp/initramfs-scripts.d/common" ]; then
    scriptsdir="/usr/share/ltsp/initramfs-scripts.d/common"
else
    exit 1
fi

for script in $(run_parts_list "$scriptsdir") ; do 
    . "$script"
done

# init=/usr/share/ltsp/initramfs-scripts can be used to launch this script,
# which should then chain to /sbin/init.
# To run it from the initramfs instead, pass any parameter, e.g.
# chroot "$rootmnt" /usr/share/ltsp/initramfs-scripts noinit
test $# -eq 0 && exec /sbin/init
