#!/bin/sh
#
#  Copyright (c) 2009 Revolution Linux
#
#  Author: Stephane Graber <stgraber@ubuntu.com>
#
#  2009, Stephane Graber <stgraber@ubuntu.com>
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, you can find it on the World Wide
#  Web at http://www.gnu.org/copyleft/gpl.html, or write to the Free
#  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#

nbdcmd=$(pgrep -l -f "/dev/nbd0" | cut -d " " -f "2-")
[ -z "${nbdcmd}" ] && exit

while :; do
    sleep 5s
    [ -n "$(pgrep -l -f '/dev/nbd0')" ] && continue
    nbd-client -c /dev/nbd0
    while [ "$?" != "1" ]; do
        nbd-client -c /dev/nbd0
    done
    ${nbdcmd}
    echo 2> /proc/sys/vm/drop_caches
done
