#!/bin/sh

# use this script to run LDM from init.

# copy this script to /etc/ldm-init
# make executable: chmod +x /etc/ldm-init

# put a line in /etc/inittab:
# L9:23:respawn:/etc/ldm-init

# install openssh-server, xbase-clients and a window manager on the server

# run on tty:
tty="7"

# set ip address of your ssh server:
export LDM_SERVER=10.2.2.2

/usr/sbin/ldm vt$tty :$(($tty-1))
