.TH "ltsp-update-sshkeys" "8" 
.SH "NAME" 
ltsp-update-sshkeys \(em Updates the LTSP server's ssh host keys on the client 
.SH "SYNOPSIS" 
.PP 
\fBltsp-update-sshkeys\fR 
.SH "DESCRIPTION" 
.PP 
\fBltsp-update-sshkeys\fR updates the current ltsp servers 
sshkeys in the client chroot.  This is required for example if the ltsp server changes 
ip address. 
.SH "SEE ALSO" 
.PP 
\fBltsp-build-client\fP\fB(8)\fP, 
\fBltsp-update-kernels\fP\fB(8)\fP. 
.SH "AVAILABILITY" 
.PP 
\fBltsp-update-sshkeys\fR is part of \fBltsp\fP package 
and the latest versions are available in source form from 
\fIhttps://launchpad.net/products/ltsp (link to URL https://launchpad.net/products/ltsp) \fR. 
.SH "MAN PAGE AUTHOR" 
.PP 
Peter Savage \- silentk \- cbx33 
debug@silentkeystroke.co.uk 
.\" created by instant / docbook-to-man, Fri 21 Apr 2006, 06:15 
