#!/bin/bash

#
# install a LTSP chroot to /opt/ltsp/$ARCH
# requires livecd-tools-015 or higher
# --kickstart <filename.ks> if you want to override any install options or use a different repository
#

case "$MODE" in
    commandline)
        add_option "kickstart" "`eval_gettext "Path to kickstart file"`" "advanced" "true" 
        add_option "cachedir"  "`eval_gettext "Path to chroot-creator cachedir"`" "advanced" "true" 
        add_option "release"  "`eval_gettext "Release version number"`" "advanced" "true" 
        add_option "distro"  "`eval_gettext "Distro name"`" "advanced" "true" 
    ;;
    configure)
        if [ -n "$option_kickstart_value" ]; then
            KICKSTART_OPT="$option_kickstart_value"
            echo "Manual Kickstart: $KICKSTART_OPT"
        else
            if [ -n "$option_release_value" ]; then
                RELEASE=$option_release_value
            else
                RELEASE=$(lsb_release -r |awk {'print $2'})
            fi
            if [ -n "$option_distro_value" ]; then
                DISTRO=$option_distro_value
            else
                DISTRO=$(lsb_release -i |awk {'print $3'})
            fi
            KICKSTART_OPT="/etc/ltsp/kickstart/$DISTRO/$RELEASE/ltsp-$ARCH.ks"
            echo "Autoconfigured Kickstart: $KICKSTART_OPT"
        fi

        if [ ! -e $KICKSTART_OPT ]; then
            echo "ERROR: $KICKSTART_OPT does not exist."
        fi

        if [ -n "$option_cachedir_value" ]; then
            CACHEDIR_OPT="--cachedir=$option_cachedir_value"
            echo "Cachedir: $option_cachedir_value"
        else
            unset CACHEDIR_OPT
        fi
    ;;
    install)
        echo "Installing into $ROOT"
        # SELINUX NOTE: proper labeling within chroot is currently not possible
        setarch $ARCH /usr/sbin/chroot-creator \
           --target=$ROOT $CACHEDIR_OPT \
           $KICKSTART_OPT
    ;;
esac
