#!/bin/bash

#
# install a LTSP chroot to /opt/ltsp/$ARCH
# requires livecd-tools-015 or higher
# --kickstart <filename.ks> if you want to override any install options or use a different repository
#

case "$MODE" in
    commandline)
        add_option "kickstart" "`eval_gettext "Path to kickstart file"`" "advanced" "true" 
        add_option "cachedir"  "`eval_gettext "Path to chroot-creator cachedir"`" "advanced" "true" 
        add_option "release"  "`eval_gettext "Release version number"`" "advanced" "true" 
        add_option "distro"  "`eval_gettext "Distro name"`" "advanced" "true" 
    ;;
    configure)
        if [ -n "$option_kickstart_value" ]; then
            KICKSTART_OPT="$option_kickstart_value"
            echo "Manual Kickstart: $KICKSTART_OPT"
        else
            . /etc/sysconfig/k12_dist
            if [ -z "$K12_DIST" ]; then
                echo "ERROR: K12_DIST not defined in /etc/sysconfig/k12_dist or elsewhere."
                exit 1
            fi
            case "$K12_DIST" in
                fc8)
                    DISTRODEF="Fedora"
                    RELEASEDEF=8
                ;;
                fc9)
                    DISTRODEF="Fedora"
                    RELEASEDEF=9
                ;;
                el5)
                    DISTRODEF="EL"
                    RELEASEDEF=5
                ;;
                *)
                    echo "ERROR: $K12_DIST is unsupported."
                    exit 1
                ;;
            esac

            if [ -n "$option_release_value" ]; then
                RELEASE=$option_release_value
            else
                RELEASE=$RELEASEDEF
            fi
            if [ -n "$option_distro_value" ]; then
                DISTRO=$option_distro_value
            else
                DISTRO=$DISTRODEF
            fi
            KICKSTART_OPT="/etc/ltsp/kickstart/$DISTRO/$RELEASE/ltsp-$ARCH.ks"
            echo "Autoconfigured Kickstart: $KICKSTART_OPT"
        fi

        if [ ! -e $KICKSTART_OPT ]; then
            echo "ERROR: $KICKSTART_OPT does not exist."
            exit 1
        fi

        if [ -n "$option_cachedir_value" ]; then
            CACHEDIR_OPT="--cachedir=$option_cachedir_value"
            echo "Cachedir: $option_cachedir_value"
        else
            unset CACHEDIR_OPT
        fi
    ;;
    install)
        echo "Installing into $ROOT"
        # SELINUX NOTE: proper labeling within chroot is currently not possible
        setarch $ARCH /usr/sbin/chroot-creator \
           --target=$ROOT $CACHEDIR_OPT \
           $KICKSTART_OPT
    ;;
esac
