#!/bin/sh

# Disable services we don't want
systemctl mask display-manager.service
systemctl disable smartd.service

# Enable services we do want
/sbin/chkconfig ltsp-core on

# Setup readonly-root Mode
#sed -i 's/READONLY=no/READONLY=yes/' /etc/sysconfig/readonly-root

# Set ltsp-launch-client as DM
#echo "DISPLAYMANAGER=/usr/sbin/ltsp-client-launch" > /etc/sysconfig/desktop

# Link /etc/mtab to /proc/self/mounts
ln -sf ../proc/self/mounts /etc/mtab

# Files to silence warning messages
touch /etc/alsa/asound.state
touch /etc/asound.state
