#!/bin/sh

# Disable services we don't want
for service in ConsoleKit avahi-daemon crond cups exim gpm iptables ip6tables \
    iscsid kudzu lvm2-monitor mcstrans mdmonitor nfs NetworkManager named\
    pcscd rpcbind rpcgssd rpcidmapd rpcsvcgssd; do
    if [ ! -e /etc/init.d/$service ]; then
        continue
    fi
    #echo "Disabling Service: $service"
    /sbin/chkconfig $service off
done

# Enable services we do want
for service in haldaemon messagebus rsyslog udev-post ltsp-core ; do
    if [ ! -e /etc/init.d/$service ]; then
        continue
    fi
    #echo "Enabling Service: $service"
    /sbin/chkconfig $service on
done

# Setup readonly-root Mode
#sed -i 's/READONLY=no/READONLY=yes/' /etc/sysconfig/readonly-root

# Set ltsp-launch-client as DM
#echo "DISPLAYMANAGER=/usr/sbin/ltsp-client-launch" > /etc/sysconfig/desktop

# Link /etc/mtab to /proc/self/mounts
ln -sf ../proc/self/mounts /etc/mtab

# Files to silence warning messages
touch /etc/alsa/asound.state
touch /etc/asound.state

# F10+: install default boot-duration so plymouth can guess the startup progress bar better
if [ -e /var/lib/plymouth/boot-duration ]; then
    cp /usr/share/ltsp/template/plymouth-default-boot-duration /var/lib/plymouth/boot-duration
fi
