#!/bin/bash
. /usr/lib/ltsp/initramfs-common

# If /dev/null does not exist, create it
[ ! -e /dev/null ] && /sbin/MAKEDEV null

detect_latest_kernel

# Only NFS is implemented in mkinitrd for now
# See /etc/sysconfig/mkinitrd to override the defaults
# The options must be in that config file so the initrd's contructed
# during kernel installation are automatically valid for LTSP.
echo "Creating Net Bootable Initial Ramdisk Image for kernel-$kernelversion"
/sbin/mkinitrd -f /boot/initrd-$kernelversion.img $kernelversion

# Set permissions
chmod 644 /boot/vmlinuz*
chmod 644 /boot/initrd*

# Symlink to latest kernel and initrd
cd /boot
ln -sf vmlinuz-$kernelversion     vmlinuz.ltsp
ln -sf  initrd-$kernelversion.img initrd.ltsp
cd - > /dev/null
