#!/bin/bash
. /usr/lib/ltsp/initramfs-common
detect_latest_kernel

# If /dev/null does not exist, create it
[ ! -e /dev/null ] && /sbin/MAKEDEV null

# Only NFS is implemented in mkinitrd for now
# NFS 192.168.0.254:/opt/ltsp/i386 is pre-defined, but the dhcp server can override this with
# option root-path "IPADDRESS:PATH";
/sbin/mkinitrd --with-avail==networking --net-dev=eth0 --rootfs nfs --rootdev=192.168.0.254:/opt/ltsp/i386 --rootopts=noatime,dhcp -f \
               /boot/initrd-$kernelversion.img $kernelversion
