.TH "ldminfod" "8" "20061023" "Vagrant Cascadian" ""
.SH "NAME"
ldminfod \(em output login sessions and available locales
.SH "SYNOPSIS"
.PP 
\fBldminfod\fR 
.SH "DESCRIPTION"
.PP 
\fBldminfod\fR will output the login sessions and locales available.  it is
usually run from an inetd(8) instance. it is used by ldm(1) to remotely
determine available login and locale settings.
.SH "EXAMPLE"
.PP 
add the following lines to /etc/inetd.conf(5):
.PP 
9571           stream  tcp     nowait  nobody /usr/sbin/tcpd /usr/sbin/ldminfod
.SH "SEE ALSO"
.PP 
ldm(1),
inetd(8),
inetd.conf(5). 
.SH "AVAILABILITY"
.PP 
\fBldminfod\fR is part of \fBltsp\fP package 
and the latest versions are available in source form from 
\fIhttps://launchpad.net/products/ltsp (link to URL https://launchpad.net/products/ltsp) \fR. 
.SH "MAN PAGE AUTHOR"
.PP 
copyright 2006 Vagrant Cascadian <vagrant@freegeek.org>, distributed under
the terms of the GNU General Public License version 2 or any later version.
