.TH "ltsp-update-kernels" "8" "2012-05-29"
.SH "NAME"
ltsp-update-kernels \- Copy LTSP chroot kernels to TFTP directories.

.SH "SYNOPSIS"
.PP
\fBltsp-update-kernels\fR [OPTION] [CHROOT...]

.SH "DESCRIPTION" 
.PP 
\fBltsp-update-kernels\fR copies the boot/ directory from LTSP chroots to
the TFTP directories in order to make them available to PXE clients.
Copying kernels from inside NBD images is also supported.
CHROOT can be a full path or a subdirectory of the /opt/ltsp base directory,
and if it's unset, all available chroots are processed.

.SH "OPTIONS"
.PP
.IP "\fB\-b\fP \fB\-\-base=\fP"
The LTSP base directory. Defaults to "/opt/ltsp".

.IP "\fB\-d\fP \fB\-\-tftp-boot-dir=\fP"
The LTSP subdirectory within the TFTP base directory.
Defaults to "ltsp".

.IP "\fB\-h\fP \fB\-\-help\fP"
The application help page.

.IP "\fB\-t\fP \fB\-\-tftp\-dirs=\fP"
Space-separated list of TFTP directories to update.
Defaults to "/var/lib/tftpboot /tftpboot /srv/tftp".

.SH "SEE ALSO" 
.PP
\fBltsp\-build\-client\fP(8),
\fBltsp\-update\-image\fP(8),
\fBltsp\-update\-sshkeys\fP(8).

.SH "AVAILABILITY"
.PP
\fBltsp\-update\-kernels\fR is part of \fBltsp\fP package and the latest
versions are available in source form from \fIhttps://launchpad.net/ltsp\fR. 

.SH "MAN PAGE AUTHOR"
.PP
Copyright 2012 Alkis Georgopoulos <alkisg@gmail.com>, distributed under
the terms of the GNU General Public License version 2 or any later version.
