.TH "ltsp-update-kernels" "8" 
.SH "NAME" 
ltsp-update-kernels \(em Updates the LTSP server kernel 
.SH "SYNOPSIS" 
.PP 
\fBltsp-update-kernels\fR 
.SH "DESCRIPTION" 
.PP 
\fBltsp-update-kernels\fR updates the current ltsp client
kernel by using the current kernel from the ltsp chroot and copying 
it to the tftpboot directory.  It also copies the initramfs across 
and sets up the PXE linux or Yaboot (PPC) boot files, depending on the  
arch of the system. 
.SH "SEE ALSO" 
.PP 
\fBltsp-build-client\fP\fB(8)\fP, 
\fBltsp-update-sshkeys\fP\fB(8)\fP. 
.SH "AVAILABILITY" 
.PP 
\fBltsp-update-kernels\fR is part of \fBltsp\fP package 
and the latest versions are available in source form from 
\fIhttps://launchpad.net/products/ltsp (link to URL https://launchpad.net/products/ltsp) \fR. 
.SH "MAN PAGE AUTHOR" 
.PP 
Peter Savage \- silentk \- cbx33 
debug@silentkeystroke.co.uk 
.\" created by instant / docbook-to-man, Fri 21 Apr 2006, 06:16 
