#! /bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH

umask 022

ACTION=$1
RCDIR=/usr/share/ldm/rc.d

case "${ACTION}" in
    start)
        SCRIPTS=$(ls ${RCDIR}/S*)
        ;;
    stop)
        SCRIPTS=$(ls ${RCDIR}/K*)
        ;;
esac

for SCRIPT in ${SCRIPTS}; do
    . ${SCRIPT}
done
