#!/bin/sh

# set hostname to ltsp if none is received from dhcp

read HOSTNAME < /proc/sys/kernel/hostname
if [ "${HOSTNAME}" = "(none)" ]; then
    HOSTNAME_BASE="ltsp"
    # get networking configuration
    . /tmp/net-*.conf
    if [ -f ${rootmnt}/etc/lts.conf ] && [ -x ${rootmnt}/usr/bin/getltscfg ]; then
        # get defaults from lts.conf
        eval $(chroot ${rootmnt} /usr/bin/getltscfg -a)
    fi
    # if HOSTNAME was not defined in lts.conf
    if [ "$HOSTNAME" = "(none)" ]; then
        case "$HOSTNAME_EXTRA" in
            mac)
                HOSTNAME_EXTRA=$(ip link show $DEVICE | awk '/ether/{print $2}' | tr ':' '-')
                ;;
            ip|"")
                HOSTNAME_EXTRA=$(echo "$IPV4ADDR.$IPV4NETMASK" | awk -F "." '{ print (($1%(256-$5)*256+$2%(256-$6))*256+$3%(256-$7))*256+$4%(256-$8) }')
                ;;
        esac
        HOSTNAME="$HOSTNAME_BASE$HOSTNAME_EXTRA"
    fi
    echo "$HOSTNAME" > /proc/sys/kernel/hostname
fi
cat /proc/sys/kernel/hostname > ${rootmnt}/etc/hostname || true
