#!/bin/sh -e
# initramfs hook for nbd

MINKVER="2.6.17"
PREREQ=""

# Output pre-requisites
prereqs()
{
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac


. /usr/share/initramfs-tools/hook-functions

# make sure all our modules are there
force_load nbd
force_load squashfs
force_load overlayfs
force_load aufs

# Copy across the binaries
copy_exec /sbin/nbd-client /sbin
copy_exec /usr/sbin/nbd-proxy /sbin/nbd-proxy
copy_exec /usr/sbin/nbd-client-proxy /sbin/nbd-client-proxy

# Work around LP bug #696435
mkdir -p ${DESTDIR}/lib/udev/rules.d
cat > ${DESTDIR}/lib/udev/rules.d/60-squashfs.rules <<EOF
KERNEL=="nbd0", ENV{ID_FS_TYPE}="squashfs"
EOF
