#!/bin/sh -e
# initramfs hook for nbd

MINKVER="2.6.17"
PREREQ=""

# Output pre-requisites
prereqs()
{
	echo "$PREREQ"
}

case "$1" in
    prereqs)
	prereqs
	exit 0
	;;
esac


. /usr/share/initramfs-tools/hook-functions

for X in squashfs unionfs nbd; do 
    manual_add_modules "${x}"
done

# make sure all our modules are there
force_load nbd
force_load squashfs
force_load unionfs

# Copy across the binaries
copy_exec /sbin/nbd-client /sbin
copy_exec /sbin/mkswap /sbin
copy_exec /sbin/swapon /sbin
copy_exec /usr/bin/tftp /bin
