#!/usr/bin/python
import sys
from subprocess import *
if __name__ == "__main__":
    # Get list of valid locales from locale -a
    try:
        lines = Popen(['locale', '-a'], stdout=PIPE).communicate()[0]

    except OSError:
        print "ERROR"
        sys.exit(0)
    langs = lines.split(None)
    for lang in langs:
        lang=lang.rstrip()
        if lang.endswith('.utf8'):
            # locale returns .utf8 when we want .UTF-8
            lang=lang.replace('.utf8','.UTF-8')
        if lang != 'POSIX' and lang != 'C':
            print lang
    print
    try:
        lines=[]
        for alternative in ['x-session-manager','x-window-manager']:
            lines.append(Popen(['update-alternatives', '--list', alternative ],
                      stdout=PIPE).communicate()[0])
    except OSError:
        print "ERROR"
        sys.exit(0)
    for line in lines:
        print line
