#!/bin/sh
#
#  Copyright (c) 2006 Canonical LTD
#
#  Author: Oliver Grawert <ogra@canonical.com>
#
#  2007, Scott Balneaves <sbalneav@ltsp.org>
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
#  USA
#

# make sure the ssh keys for ldm are freshly copied to the
# ltsp client chroot so we avoid breakage if the IP changed

[ "$IFACE" != "lo" ] || exit 0

test -f /usr/sbin/ltsp-update-sshkeys || exit 0

/usr/sbin/ltsp-update-sshkeys >/dev/null 2>&1 || true
