#!/bin/sh

#  Copyright (c) 2012, Alkis Georgopoulos <alkisg@gmail.com>
#  Copyright (c) 2012, Vagrant Cascadian <vagrant@freegeek.org>

#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, you can find it on the World Wide
#  Web at http://www.gnu.org/copyleft/gpl.html, or write to the Free
#  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
#  MA 02110-1301, USA.

conf=/etc/dnsmasq.d/ltsp-server-dnsmasq.conf
template=/usr/share/ltsp/ltsp-server-dnsmasq.conf

test -f "$conf" && exit 0

cp "$template" "$conf"

ip route show | while read line; do
    subnet=${line%%/*}
    case "$subnet" in
        127.0.0.1|169.254.0.0|192.168.67.0|*[!0-9.]*)
            # do nothing on these networks
            ;;
    	*) 
            echo "dhcp-range=$subnet,proxy" >> "$conf"
            ;;
    esac
done

invoke-rc.d dnsmasq restart
