#!/bin/sh
#
#  Copyright (c) 2006 Vagrant Cascadian <vagrant@freegeek.org>
#
#  2006, Oliver Grawert <ogra@canonical.com>
#  2008, Warren Togami <wtogami@redhat.com>
#        Vagrant Cascadian <vagrant@freegeek.org>
#        Eric Harrison <eharrison@k12linux.mesd.k12.or.us>
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
#  USA
#


# generates a swap file and configures nbd-server to export it
# to stdout. should usually be run from an inetd.

# default to running mkswap 
RUN_MKSWAP=true

if [ -f /etc/ltsp/nbdswapd.conf ]; then
    . /etc/ltsp/nbdswapd.conf
fi

# Abort if liveimg
cat /proc/cmdline |/bin/grep -q "liveimg"
[ $? -eq 0 ] && exit 0

# swapfile size (in MB)
SIZE=${SIZE:-"32"}

if [ -n "$SWAPDIR" ]; then
    if [ -d "$SWAPDIR" ] && [ -w "$SWAPDIR" ]; then
        TEMPFILE_OPTS="${SWAPDIR}/XXXXXX"
    else
        echo "ERROR: not a directory or not writeable: $SWAPDIR" >&2
        exit 1
    fi
fi

if [ -z "$SWAP" ]; then
    SWAP=$(mktemp $TEMPFILE_OPTS)
fi

# generate the swap file
dd if=/dev/zero of=$SWAP bs=1024k count=0 seek=$SIZE 2> /dev/null

if [ "$RUN_MKSWAP" = "true" ]; then
    /sbin/mkswap $SWAP > /dev/null 2>&1
fi

# start the swap server
PATH=/usr/bin:/bin:$PATH nbd-server 0 $SWAP $NBD_SERVER_OPTS -C /dev/null > /dev/null 2>&1

# clean up the swap file
rm -f $SWAP
