#!/bin/sh

### Set Runlevel 5 and turn off the mingetty's
# Fedora 8 and previous, and RHEL5 
[ -e /etc/inittab ] && sed -i 's/^id:3/id:5/; /^[1-6].*/d;' /etc/inittab
# Fedora 9+ with Upstart
if [ -e /etc/event.d/tty1 ]; then
    for NUM in 1 2 3 4 5 6; do
        echo > /etc/event.d/tty$NUM
    done
fi        
# Fedora 13+ and EL6 with Upstart
if [ -e /etc/init/start-ttys.conf ]; then
    echo > /etc/init/start-ttys.conf
fi
