#!/bin/sh
LANG=C

do_ssh(){
    ssh -S $LDM_SOCKET $LDM_SERVER "$@"
}

do_scp(){
    scp -o "ControlPath $LDM_SOCKET" -o "User $USER" $1 $2
}

generate() {
    if [ -z ${TMP_XDG_DIR} ]; then
        exit
    fi

    # Make the working directory and subdirs
    for d in applications icons; do
        do_ssh mkdir -p "${TMP_XDG_DIR}/${d}"
    done

    # Build desktop file list
    if [ -n "${LOCAL_APPS_MENU_ITEMS}" ]; then
        DESKTOP_FILES=""
        IFS=,
        for i in ${LOCAL_APPS_MENU_ITEMS}; do 
            if [ -e "/usr/share/applications/${i}.desktop" ]; then 
                DESKTOP_FILES="${DESKTOP_FILES} /usr/share/applications/${i}.desktop" 
            fi
        done
        unset IFS
    else
        DESKTOP_FILES=/usr/share/applications/*.desktop
    fi

    # Cycle through all .desktop files in client's system applications dir
    for a in ${DESKTOP_FILES}; do
        # Copy client's .desktop file to local
        do_scp ${a} ${LDM_SERVER}:${TMP_XDG_DIR}/applications/${a##*/}

        # Change Exec and TryExec to our localapps command
        do_ssh sed -i -e 's/^TryExec=\(.*\)/TryExec=xprop -root -f LTSP_COMMAND 8s -set LTSP_COMMAND "\1"/' -e 's/^Exec=\(.*\)/Exec=xprop -root -f LTSP_COMMAND 8s -set LTSP_COMMAND "\1"/' ${TMP_XDG_DIR}/applications/${a##*/} 

        # Find the appropriate icon and copy it into the local icons dir
        ICON=$(grep ^Icon ${a}|sed -e 's/^Icon=\(.*\)/\1/')

        # If icon is relative path, try to copy from /usr/share/pixmaps
        # If icon is absolute path, try to copy from absolute path
        # Else don't copy an icon
        if [ -n "${ICON}" ] && [ "${ICON}" = "${ICON##*/}" ]; then
            ICON=$(find -L /usr/share/icons /usr/share/pixmaps -type f -regex '.*'${ICON}'.*[png|xpm|svg]?'|head -1)
            do_scp ${ICON} ${LDM_SERVER}:${TMP_XDG_DIR}/icons/${ICON##*/}
        else
            [ -e ${ICON} ] && do_scp ${ICON} ${LDM_SERVER}:${TMP_XDG_DIR}/icons/${ICON##*/} 
        fi
    done
    true
}

remove() {
    if [ -n "${TMP_XDG_DIR}" ];then
        do_ssh rm -rf "${TMP_XDG_DIR}" 
    fi
    true
}

case "$1" in
    install)
        remove
        generate
    ;;
    remove)
        remove
    ;;
    *)
        echo "Usage: $0 install|remove"
        exit
    ;;
esac
