#!/bin/sh
# We depend on network modules being loaded
[ "$1" = "-d" ] && echo network

# If our prerequisites are not met, fail anyways.
which mount.fuse mount.unionfs unionfs umount >/dev/null 2>&1 || exit 1

exit 255
