#!/bin/sh
# Depend on the ldm package
#
# Copyright 2005, Canonical Ltd.
# 
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License with your
# Debian GNU system, in /usr/share/common-licenses/GPL.  If not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.


#
# Load ltsp config defaults
#

. /usr/lib/ltsp/ltsp_config

#
# Set up path
#

PATH=$PATH:/usr/bin/X11

#
# Custom xorg.conf file?
#

[ ! -z "${XORG_CONF}" ] && [ -f ${XORG_CONF} ] && \
    cp ${XORG_CONF} /etc/X11/xorg.conf

#
# Compute tty and displaynum
#

tty=$(tty)
case "$tty" in
  /dev/tty*) # with udev (2.6 kernel)
      ttynum=${tty#/dev/tty}
      ;;
  /dev/vc/*) # with devfs (2.4 kernel)
      ttynum=${tty#/dev/vc/}
      ;;
esac
displaynum=$(($ttynum - 1))

while true; do
    #
    # Server scalability.  If there exists a /usr/lib/ltsp/get_hosts file, then
    # use it to populate the LDM_SERVER environment variable.
    #

    if [ -x /usr/lib/ltsp/get_hosts ] ; then
        export LDM_SERVER=$(/usr/lib/ltsp/get_hosts)
    fi

    #
    # Loop though each of the hosts, and get their ldminfo
    #

    if [ "x$LDM_SERVER" != "x" ]; then
        if [ ! -d /tmp/ldm ] ; then
            mkdir -p /tmp/ldm
        fi
        for SRV in $LDM_SERVER ; do
            nc $SRV 9571 > /tmp/ldm/$SRV
        done
    fi
        
    ldm vt$ttynum :$displaynum
done
