#!/bin/sh
#
# Copyright (c) 2002 by James A. McQuillan (McQuillan Systems, LLC)
#
# This software is licensed under the Gnu General Public License version 2,
# the full text of which can be found in the COPYING file.
#

#
# Fire up a shell on this tty
#

echo "tty=" `tty`

if [ -x /usr/bin/openvt ]; then
    openvt=/usr/bin/openvt
elif [ -x /bin/openvt ]; then
    openvt=/bin/openvt
else
    exec /bin/bash --login
fi

exec $openvt -c $SCREEN_NUM -f -w -l /bin/bash
