#!/bin/bash
#
# Copyright (c) 2002 by James A. McQuillan (McQuillan Systems, LLC)
#
# This software is licensed under the Gnu General Public License.
# The full text of which can be found at http://www.LTSP.org/license.txt
#

#
# Fire up a shell on this tty
#

echo "tty=" `tty`

exec /bin/bash --login
