#!/bin/sh
#
# Script for starting one or more ssh sessions
#

#
# Get the lts.conf entries, and assign them to shell
# variables.
#
if [ "True" != "$LTSP_CONFIG" ]; then
    . /usr/share/ltsp/ltsp_config
fi

#
# Get the IP address of the host to ssh into.
# First look for 'SSH_HOST', if not specified, then
# look for 'SERVER'. If that isn't specified, then use
# the default of '192.168.0.254'
#

unset SSH_ARGS
if [ $# -ge 1 ]; then
    SSH_ARGS=$*
else
    SSH_HOST=${SSH_HOST:-${SERVER}}
fi
SSH_ARGS="$SSH_ARGS $SSH_HOST"

export TERM=linux           # Setup the terminal type

TTY=$(fgconsole)
chvt ${TTY}

# Clear the screen, to place cursor at the top
clear

# Get the username
echo -n "Username: "
read SSH_USER

SSH_ARGS="$SSH_ARGS -l $SSH_USER"

# Launch ssh 
ssh ${SSH_ARGS}

if [ "$?" != 0 ]; then
    # Brief pause, in case ssh had errors to report
    echo -n "Please wait..."
    sleep 1
fi
