#!/bin/sh
#
# Screen script that launches xterm, mainly for troubleshooting.
#
# Copyright (c) 2011 Alkis Georgopoulos <http://alkisg.mysch.gr>
#
# This software is licensed under the GNU General Public License version 2,
# the full text of which can be found in the COPYING file.

. /usr/share/ltsp/screen-x-common
 
if [ -x /usr/share/ltsp/xinitrc ]; then
    xinitrc=/usr/share/ltsp/xinitrc
fi

export HOME="${HOME:-/root}" USER="${USER:-root}"

if ! xinit $xinitrc xterm "$@" -- "$DISPLAY" "vt${TTY}" $X_ARGS; then
    echo "Xserver failed, falling back to a text shell" >&2
    exec /bin/bash --login
fi
