#!/bin/sh

# Read options from /etc/ltsp/vmclient
[ -f /etc/ltsp/vmclient ] && . /etc/ltsp/vmclient

set -x
qemu-kvm -hda /dev/null -boot n -m 256 $VGAOPTION $NICMODEL -net tap,script=/usr/sbin/ltsp-qemu-bridge-ifup
