#!/bin/sh

# vmwarevga is better than cirrus or vesa
strings /usr/bin/qemu-kvm |grep vmwarevga > /dev/null
[ $? -eq 0 ] && VGAOPTION="-vmwarevga"

# e1000 is much better than the default rtl8139
[ -e /usr/share/kvm/pxe-e1000.bin ] && NICMODEL=",model=e1000" 

qemu-kvm -hda /dev/null -boot n -m 256 $VGAOPTION -net nic$NICMODEL -net tap,script=/usr/sbin/ltsp-qemu-bridge-ifup
