#!/bin/bash

set -x

case "$MODE" in
    commandline)
        add_option "release"  "`eval_gettext "Release version number"`" "advanced" "true"
    ;;
    configure)
        /usr/sbin/usermod -a -G mock nobody
        BUILD=${BUILD:-x86_64}
        ARCH=${ARCH:-$(echo $BUILD | sed -e s/i.86/i386/)}
        MOCK_CMD="setarch $BUILD /usr/bin/mock -r ltsp-$ARCH --target=$BUILD --configdir=/etc/ltsp/mock --arch=$BUILD"
    ;;
    install)
        $MOCK_CMD --scrub=all
        $MOCK_CMD --init
        $MOCK_CMD --shell "touch /etc/ltsp_chroot"
        $MOCK_CMD --shell "yum group install 'X Window System'"
        $MOCK_CMD --install ltsp-client ldm ldminfod nbd ltspfs tftp dracut-tools xterm x2goclient freerdp fuse-sshfs busybox xterm pulseaudio e2fsprogs pulseaudio xorg-x11-fonts firefox dbus-x11 evince telnet nfs-utils GConf2
    ;;
    after-install)
        $MOCK_CMD --shell "[ -d /etc/ltsp ] || echo LTSP client not installed"
        $MOCK_CMD --copyin /etc/ltsp/dracut/ltsp-dracut.conf /etc/dracut.conf.d/ltsp-dracut.conf
        $MOCK_CMD --copyin /etc/ltsp/dracut/sysconfig-network /etc/sysconfig/network
        $MOCK_CMD --copyin /etc/ltsp/dracut/ifcfg-eth0 /etc/sysconfig/network-scripts/ifcfg-eth0
        $MOCK_CMD --copyin /etc/adjtime /etc/adjtime
        $MOCK_CMD --copyin /etc/vconsole.conf /etc/vconsole.conf
        mv $BASE/mock/$ARCH/root $ROOT
        ln -s $ROOT $BASE/mock/$ARCH/root
        cp $ROOT/etc/skel/.bash* $ROOT/root/
        cat << EOF >> $ROOT/root/.bashrc
PS1="<LTSP $ARCH> [\u@\h \W]\\\\$ "
EOF
    ;;
esac
