#!/bin/sh
MEMTOTAL=$(grep ^MemTotal /proc/meminfo | awk '{print $2}')
CPUFREQ=$(grep "^cpu MHz" /proc/cpuinfo | head -n1 | awk '{print $4}')
CPUNAME=$(grep "^model name" /proc/cpuinfo | head -n1 | sed "s/.*: //g")
CPUCOUNT=$(grep ^processor /proc/cpuinfo | wc -l)
CPUVENDOR=$(grep "^vendor_id" /proc/cpuinfo | head -n1 | sed "s/.*: //")
PCIID=$(lspci -n | awk '{print $3}' | tr ' ' '\n' | sort | uniq -c)
echo MEMTOTAL=$MEMTOTAL
echo CPUFREQ=$CPUFREQ
echo CPUNAME=$CPUNAME
echo CPUCOUNT=$CPUCOUNT
echo CPUVENDOR=$CPUVENDOR
for id in $PCIID
do
	echo PCIID=$id
done
