#!/bin/sh -e
# initramfs hook for nbd

MINKVER="2.6.17"
PREREQ=""

# Output pre-requisites
prereqs()
{
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac


. /usr/share/initramfs-tools/hook-functions

# make sure all our modules are there
manual_add_modules nbd
manual_add_modules squashfs
manual_add_modules overlayfs
manual_add_modules aufs
auto_add_modules net

# Copy across the binaries
copy_exec /sbin/nbd-client /sbin
copy_exec /usr/sbin/nbd-proxy /sbin/nbd-proxy
copy_exec /usr/sbin/nbd-client-proxy /sbin/nbd-client-proxy
