#!/bin/sh -e
#
# udev script for ltsp-sound

(
	[ -r "/usr/share/ltsp/ltsp_config" ] && . /usr/share/ltsp/ltsp_config
	[ -r "/usr/share/ltsp/ltsp-init-common" ] && . /usr/share/ltsp/ltsp-init-common
	DEV_BASENAME="${DEVNAME##*/}"
	N="${DEV_BASENAME#controlC}"
	[ -x "/sbin/alsa-utils" ] && /sbin/alsa-utils start $N
	configure_sound_volume $N
) &

