.TH "ltsp-genmenu" "1" 20090511
.SH "NAME" 
ltsp-genmenu \(em generate menu for LTSP local applications

.SH "SYNOPSIS" 
.PP 
\fBltsp-genmenu\fR install

.SH "DESCRIPTION" 
.PP 
\fBltsp-genmenu\fR creates a menu of applications that are available as LTSP
local applications. It it used to temporarily override default menu items with
LTSP local applications. \fBltsp-genmenu\fR creates a temporary directory
structure containing modified .desktop files, which is then set to the
preferred XDG directory by use of the XDG_DATA_DIRS environment variable.

.SH "SEE ALSO" 
.PP 
\fBltsp-localapps\fP\fB(1)\fP.

.SH "AVAILABILITY" 
.PP 
\fBltsp-genmenu\fR is part of the \fBltsp\fP package and the latest versions
are available in source form from \fIhttps://launchpad.net/products/ltsp\fR. 

.SH "MAN PAGE AUTHOR" 
.PP 
Copyright 2009 Vagrant Cascadian <vagrant@freegeek.org>, distributed under
the terms of the GNU General Public License version 2 or any later version.
