.TH "xatomwait" "1" 20090511
.SH "NAME" 
xatomwait \(em poll for changes in X properties

.SH "SYNOPSIS" 
.PP 
\fBxatomwait\fR X_PROPERTY

.SH "DESCRIPTION" 
.PP 
\fBxatomwait\fR polls for changes to the specified X property (also known as X
atoms).  When a change is detected, it prints the contents of the X property
and exits.

.SH "SEE ALSO" 
.PP 
\fBxprop\fP\fB(1)\fP 

.SH "AVAILABILITY" 
.PP 
\fBxatomwait\fR is part of the \fBltsp\fP package and the latest versions are
available in source form from \fIhttps://launchpad.net/products/ltsp\fR. 

.SH "MAN PAGE AUTHOR" 
.PP 
Copyright 2009 Vagrant Cascadian <vagrant@freegeek.org>, distributed under
the terms of the GNU General Public License version 2 or any later version.
