#!/bin/sh

# Exit immediately if this is not a LTSP client chroot.
[ ! -e /etc/ltsp_chroot ] && exit 0

for i in /usr/share/ltsp/chroot-setup.d/* ; do
    [ -d $i ] && continue
    if [ -x $i ]; then
        $i
    fi
done
