#!/bin/sh

#
# Change this to suite your hosts
#
HOSTS="192.168.0.254 192.168.0.253 192.168.0.252 192.168.0.251"

# Genrate a random number
SEED=$(dd if=/dev/random bs=128 count=1 2>/dev/null | cksum | cut -d' ' -f1)


# How many hosts are listed?
COUNT=0
for I in ${HOSTS}; do
    COUNT=$(expr $COUNT + 1)
done

# A random host index
RAND=$(expr $SEED % $COUNT)

# pick the random host
I=0
for HOST in $HOSTS; do
    RANDHOST=$HOST
    if [ $I -eq $RAND ]; then
        break
    fi
    I=$(expr $I + 1)
done

# generate the host list, random host first
HOSTLIST="$RANDHOST"
for HOST in $HOSTS; do
    if [ "$HOST" = "$RANDHOST" ]; then
        continue
    fi
    HOSTLIST="$HOSTLIST $HOST"
done

# print result
echo $HOSTLIST
